- hosts: all
  become: yes
  vars:
   repository: https://github.com/NisargaG/InfraAutomation.git
  tasks:

    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add repo for nodesource
      apt_repository:
       repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
       update_cache: yes

    - name: install nodejs
      apt: name=nodejs

    - name: install nodejs-legacy
      apt: name=nodejs-legacy

    - name: install npm
      apt: name=npm

    - name: Git Clone Repo
      git:
       repo: "{{repository}}"
       dest: /home/dxcadmin/wsqc

    - name: Running NPM install
      npm: path=/home/dxcadmin/wsqc/
      register: npm_finished

    - name: Start nodejs
      shell: chdir=/home/dxcadmin/wsqc/ nohup npm start &
